- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE.txt
- README.md
- SECURITY.md
> Adding some documentation on how to use, contribute and be a memeber of

- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/embedding/store/WeaviateEmbeddingStoreProviderRegistrar.java
> Adding the runtime package dependecy for Weaviate embedding store

- pom.xml
* updated onnxruntime to 1.20.0
* updated djl to 0.30.0
* updated langchain4j to 0.36.1
* updated org.jetbrains.kotlin:kotlin-stdlib-jdk8 to v1.9.25
> Updating to langChain4J 0.36.1

- pom.xml
Updating WildFly to 34.0.1
Updating Neo4J to 5.26.3
Updating OpenAI to 0.24.0
UpdatingGalleon plugins to 7.3.1
> Updating jboss-parent to 47

- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/AILogger.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/AILogger.java
Fix ID of incorrectLLMConfiguration since 1 was never really used and related cleanup.
> Logger cleanup.

- ai-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/ai/injection/main/module.xml
- ai-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/ai/main/module.xml
- pom.xml
- wildfly-ai/injection/pom.xml
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/WildFlyLLMConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyMistralAiChatModelLanguage.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyOllamaChatModelConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyOpenAiChatModelConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/observability/OpenTelemetryMetricsChatModelListener.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/observability/OpenTelemetryTracesChatModelListener.java
- wildfly-ai/injection/src/main/resources/META-INF/beans.xml
- wildfly-ai/subsystem/pom.xml
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/AISubsystemRegistrar.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/Capabilities.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/chat/AbstractChatModelProviderServiceConfigurator.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/chat/OllamaChatModelProviderServiceConfigurator.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/chat/OpenAIChatModelProviderServiceConfigurator.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/deployment/AIDependencyProcessor.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/deployment/AIDeploymentProcessor.java
* Adding support for traces
* Adding support for metrics
> Using telemetry instrumentation in injection module to track LLM Usage.

- ai-feature-pack/src/main/resources/layers/standalone/ai/layer-spec.xml
- ai-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/ai/injection/main/module.xml
- pom.xml
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/WildFlyLLMConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyChatModelConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyMistralAiChatModelLanguage.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyOllamaChatModelConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyOpenAiChatModelConfig.java
Issue: https://github.com/wildfly-extras/wildfly-ai-feature-pack/issues/52
> Fixing issue #52: Making OpenTelemetry provisioning optional.

- README.md
- ai-feature-pack/src/main/resources/layers/standalone/groq-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/openai-chat-model/layer-spec.xml
Fixing [issue #63](https://github.com/wildfly-extras/wildfly-ai-feature-pack/issues/63) and issue [#62](https://github.com/wildfly-extras/wildfly-ai-feature-pack/issues/62)
> Adding a dedicated Groq layer

- ai-feature-pack/pom.xml
- ai-feature-pack/src/main/resources/modules/system/layers/base/dev/langchain4j/main/module.xml
- ai-feature-pack/src/main/resources/modules/system/layers/base/dev/langchain4j/ollama/main/module.xml
- pom.xml
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyMistralAiChatModelLanguage.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyOllamaChatModelConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyOpenAiChatModelConfig.java
Changing Ollama module to use JDK HttpClient
Fixing https://github.com/wildfly-extras/wildfly-ai-feature-pack/issues/68
> Updating LangChain4J to 1.0.0-beta1.

- ai-feature-pack/src/main/resources/layers/standalone/ollama-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/ollama-streaming-chat-model/layer-spec.xml
Signed-off-by: Emmanuel Hugonnet <ehugonne@redhat.com>
> Fixing attribute name

- wildfly-ai/subsystem/pom.xml
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/deployment/AIDependencyProcessor.java
Fixing issue https://github.com/wildfly-extras/wildfly-ai-feature-pack/issues/85
> Adding support to detect dependencies defined on the RegisterAIService annotations

- wildfly-mcp/subsystem/src/main/java/org/wildfly/extension/mcp/server/PromptMessageHandler.java
- wildfly-mcp/subsystem/src/main/java/org/wildfly/extension/mcp/server/ResourceMessageHandler.java
- wildfly-mcp/subsystem/src/main/java/org/wildfly/extension/mcp/server/ToolMessageHandler.java
This should fix https://github.com/wildfly-extras/wildfly-ai-feature-pack/issues/88
> Allowing for optional arguments

- README.md
> Updating doc for latest layers: MCP clients, Noe4J content retriever and

- ai-feature-pack/pom.xml
- ai-feature-pack/src/main/resources/modules/system/layers/base/com/knuddels/jtokkit/main/module.xml
- ai-feature-pack/src/main/resources/modules/system/layers/base/com/squareup/retrofit2/main/module.xml
- ai-feature-pack/src/main/resources/modules/system/layers/base/dev/langchain4j/embeddings/all-minilm-l6-v2-q/main/module.xml
- ai-feature-pack/src/main/resources/modules/system/layers/base/dev/langchain4j/main/module.xml
- ai-feature-pack/src/main/resources/modules/system/layers/base/dev/langchain4j/openai/main/module.xml
- pom.xml
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyGithubModelChatModelConfig.java
- wildfly-ai/subsystem/pom.xml
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/chat/ChatModelConnectionCheckerOperationHandler.java
Signed-off-by: Emmanuel Hugonnet <ehugonne@redhat.com>
> Upgrading to LangChain4J 1.0.0-beta2

- wildfly-mcp/injection/pom.xml
Your branch is up to date with 'origin/edburns/trival-typo-fix'.
modified:   wildfly-mcp/injection/pom.xml
> On branch edburns/trival-typo-fix

- ai-feature-pack/src/main/resources/layers/standalone/gemini-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/gemini-streaming-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/github-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/github-streaming-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/groq-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/groq-streaming-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/mistral-ai-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/mistral-ai-streaming-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/ollama-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/ollama-streaming-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/openai-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/openai-streaming-chat-model/layer-spec.xml
- pom.xml
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/WildFlyBeanRegistry.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/WildFlyLLMConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyChatModelConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyGeminiChatModelConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyGithubModelChatModelConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyMistralAiChatModelLanguage.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyOllamaChatModelConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/chat/WildFlyOpenAiChatModelConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/retriever/Neo4JContentRetrieverConfig.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/deployment/AIDependencyProcessor.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/deployment/AIDeploymentProcessor.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/rag/retriever/Neo4JContentRetrieverProviderServiceConfigurator.java
* Upgrading to LangChain4J 1.0.0-beta4 and1.0.0-cr1
* Upgrading to smallrye-llm 0.0.6
> Upgrading to LangChain4J 1.0.0-beta4:

- ai-feature-pack/src/main/resources/layers/standalone/chat-memory-provider/layer-spec.xml
- pom.xml
- wildfly-ai/injection/pom.xml
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/AILogger.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/WildFlyBeanRegistry.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/WildFlyLLMConfig.java
- wildfly-ai/injection/src/main/java/org/wildfly/extension/ai/injection/memory/WildFlyChatMemoryProviderConfig.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/AISubsystemRegistrar.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/AISubsystemSchema.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/Capabilities.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/deployment/AIAttachments.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/deployment/AIDependencyProcessor.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/deployment/AIDeploymentProcessor.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/memory/ChatMemoryProviderRegistrar.java
- wildfly-ai/subsystem/src/main/java/org/wildfly/extension/ai/memory/ChatMemoryProviderServiceConfigurator.java
- wildfly-ai/subsystem/src/main/resources/org/wildfly/extension/ai/LocalDescriptions.properties
- wildfly-ai/subsystem/src/main/resources/schema/wildfly-ai_1_0.xsd
- wildfly-ai/subsystem/src/test/resources/org/wildfly/extension/ai/ai-1.0.xml
Fixing issue with ChatMemory by creating a resource to configure a ChatMemoryProvider
> Upgrading LangChain4J to 1.0.1

- ai-feature-pack/src/main/resources/layers/standalone/mcp-client-stdio/layer-spec.xml
user MUST create a cli script to set proper values
> Fixing the layer so that it can be provisionned even if in the end the

- ai-feature-pack/src/main/resources/layers/standalone/gemini-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/gemini-streaming-chat-model/layer-spec.xml
- ai-feature-pack/src/main/resources/layers/standalone/in-memory-embedding-store/layer-spec.xml
- doc/glow-layer-doc/gemini-chat-model/env.yaml
- doc/glow-layer-doc/gemini-streaming-chat-model/env.yaml
Adding the missing Gemini documentation
Updating Gemini default model name.
> fix: issue #153

- .github/workflows/ci.yml
- pom.xml
Fixing issue https://github.com/wildfly-extras/wildfly-ai-feature-pack/issues/185
> fix: issue #185 Adding support for Java 25
